service: puppet-pdf

plugins:
  - serverless-offline
  - serverless-apigw-binary

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  stage: ${opt:stage, 'development'}
  environment:
    ENV: ${self:provider.stage}
  apiGateway:
    shouldStartNameWithService: true

custom:
  apigwBinary:
    types:
      - '*/*'

functions:
  pdf-post-html:
    handler: pdf.generate_pdf_post_html
    events:
      - httpApi:
          method: post
          path: /api/pdfhtml