org: dustbuster
app: puppet-pdf

service: puppet-pdf

provider:
  name: aws
  runtime: nodejs16.x
  region: us-west-2
  stage: ${opt:stage, 'development'}
  environment:
    ENV: ${self:provider.stage}
  apiGateway:
    shouldStartNameWithService: true

custom:
  sourcemaps: false
  copyFiles:
    - from: 'node_modules/puppeteer-core/lib/cjs/puppeteer/common/Browser'
    - to: ./bin
    - from: 'node_modules/chrome-aws-lambda/bin/chromium.br'
    - to: './bin'

package:
  patterns:
    - '!pdf2.js'
    - '!.git/**'
    - '!pdf2.ts'
    - '!tests/**'
    - '!.cache/**'
    - 'node_modules/**'

functions:
  pdf-post-html:
    handler: pdf.generate_pdf_post_html
    events:
      - httpApi:
          method: post
          path: /api/pdfhtml