org: dustbuster
app: puppet-pdf

service: puppet-pdf

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  stage: ${opt:stage, 'development'}
  lambdaHashingVersion: 20200924
  environment:
    ENV: ${self:provider.stage}
  apiGateway:
    shouldStartNameWithService: true

custom:
  apigwBinary:
    types:
      - '*/*'

functions:
  pdf-post-html:
    handler: pdf.generate_pdf_post_html
    events:
      - httpApi:
          method: post
          path: /api/pdfhtml